# Generated by Django 4.1.7 on 2023-05-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_productdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hardwaredata',
            new_name='categorydata',
        ),
    ]
