# Generated by Django 4.1.7 on 2023-05-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_rename_hardwaredata_categorydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoicedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(blank=True, max_length=100, null=True)),
                ('Emailid', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
