# Generated by Django 4.1.7 on 2023-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(blank=True, max_length=30, null=True)),
                ('Pname', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
