# Generated by Django 4.1.7 on 2023-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0002_cartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='Pimage',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
