# Generated by Django 4.1.7 on 2023-05-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0003_cartdata_pimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdata',
            name='Pimage',
        ),
    ]
